import mongoose, { Schema, Document, Types } from 'mongoose';

/**
 * One-time authentication tokens generated by the owner (DB admin role).
 * Once accepted they are marked as used and cannot be reused.
 */
export interface IAuthToken extends Document {
  _id: Types.ObjectId;
  token: string;
  /** Target username — the user that will be created/bound on acceptance */
  username: string;
  displayName: string;
  /** Whether the token has been consumed */
  used: boolean;
  /** Who generated this token */
  createdBy: Types.ObjectId;
  expiresAt: Date;
  createdAt: Date;
}

const AuthTokenSchema = new Schema<IAuthToken>(
  {
    token: { type: String, required: true, unique: true },
    username: {
      type: String,
      required: true,
      lowercase: true,
      trim: true,
      match: /^[a-z0-9_]{2,40}$/,
    },
    displayName: { type: String, required: true, maxlength: 60 },
    used: { type: Boolean, default: false },
    createdBy: { type: Schema.Types.ObjectId, ref: 'User', required: true },
    expiresAt: { type: Date, required: true },
  },
  { timestamps: { createdAt: true, updatedAt: false } },
);

AuthTokenSchema.index({ token: 1 }, { unique: true });
AuthTokenSchema.index({ expiresAt: 1 }, { expireAfterSeconds: 0 }); // TTL index

export const AuthToken = mongoose.model<IAuthToken>('AuthToken', AuthTokenSchema);
