import mongoose, { Schema, Document, Types } from 'mongoose';

/**
 * Invite tokens generated by admin/owner users.
 * Supports multi-use tokens (maxUses > 1) and optional per-email targeting.
 * Tokens can be revoked before use.
 */
export interface IInviteToken extends Document {
  _id: Types.ObjectId;
  token: string;
  /** Optional target email (informational; not enforced on accept) */
  email?: string;
  /** Who generated this token */
  createdBy: Types.ObjectId;
  /** When the token expires */
  expiresAt: Date;
  /** Maximum number of times this token can be accepted */
  maxUses: number;
  /** How many times it has already been accepted */
  uses: number;
  /** Set when an admin explicitly revokes the token */
  revokedAt?: Date;
  createdAt: Date;
}

const InviteTokenSchema = new Schema<IInviteToken>(
  {
    token: { type: String, required: true, unique: true },
    email: { type: String, trim: true, lowercase: true, maxlength: 254 },
    createdBy: { type: Schema.Types.ObjectId, ref: 'User', required: true },
    expiresAt: { type: Date, required: true },
    maxUses: { type: Number, required: true, default: 1, min: 1 },
    uses: { type: Number, required: true, default: 0, min: 0 },
    revokedAt: { type: Date },
  },
  { timestamps: { createdAt: true, updatedAt: false } },
);

InviteTokenSchema.index({ token: 1 }, { unique: true });
InviteTokenSchema.index({ expiresAt: 1 }, { expireAfterSeconds: 0 }); // TTL cleanup
InviteTokenSchema.index({ createdBy: 1 });

/** Returns true if the token is still valid (not expired, not revoked, uses not exhausted) */
InviteTokenSchema.methods['isValid'] = function (this: IInviteToken): boolean {
  if (this.revokedAt) return false;
  if (this.expiresAt < new Date()) return false;
  if (this.uses >= this.maxUses) return false;
  return true;
};

export const InviteToken = mongoose.model<IInviteToken>('InviteToken', InviteTokenSchema);
