import { useState } from 'preact/hooks';

export function LoginPage() {
  const [mode, setMode] = useState<'invite' | 'anonymous'>('invite');
  const [token, setToken] = useState('');
  const [displayName, setDisplayName] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  const handleInvite = async (e: Event) => {
    e.preventDefault();
    setError('');
    setLoading(true);
    try {
      const res = await fetch('/api/auth/accept', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ token }),
      });
      const data = await res.json() as { sessionToken?: string; error?: string };
      if (!res.ok) throw new Error(data.error ?? 'Failed to authenticate');
      localStorage.setItem('sessionToken', data.sessionToken!);
      window.location.reload();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Authentication failed');
    } finally {
      setLoading(false);
    }
  };

  const handleAnonymous = async (e: Event) => {
    e.preventDefault();
    setError('');
    if (!displayName.trim()) {
      setError('Display name is required for anonymous access');
      return;
    }
    setLoading(true);
    try {
      const res = await fetch('/api/auth/anonymous', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ displayName: displayName.trim() }),
      });
      const data = await res.json() as { sessionToken?: string; error?: string };
      if (!res.ok) throw new Error(data.error ?? 'Failed to create session');
      localStorage.setItem('sessionToken', data.sessionToken!);
      window.location.reload();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Session creation failed');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div class="login-page">
      <div class="login-card">
        <div class="login-logo">
          <svg width="48" height="48" viewBox="0 0 28 28" fill="none" aria-hidden="true">
            <rect width="28" height="28" rx="6" fill="#e94560" />
            <rect x="6" y="8" width="16" height="2" rx="1" fill="white" />
            <rect x="6" y="13" width="12" height="2" rx="1" fill="white" />
            <rect x="6" y="18" width="8" height="2" rx="1" fill="white" />
          </svg>
          <h1>Excalidraw Slides</h1>
        </div>

        <div class="login-tabs">
          <button
            class={`tab-btn ${mode === 'invite' ? 'active' : ''}`}
            onClick={() => setMode('invite')}
          >
            Invite Link
          </button>
          <button
            class={`tab-btn ${mode === 'anonymous' ? 'active' : ''}`}
            onClick={() => setMode('anonymous')}
          >
            View as Guest
          </button>
        </div>

        {mode === 'invite' ? (
          <form onSubmit={handleInvite} class="login-form">
            <label htmlFor="invite-token">Invite token</label>
            <input
              id="invite-token"
              type="text"
              placeholder="Paste your invite token here"
              value={token}
              onInput={(e) => setToken((e.target as HTMLInputElement).value)}
              required
              autocomplete="off"
            />
            <p class="login-hint">An invite token is generated by your team owner.</p>
            {error && <p class="error-msg" role="alert">{error}</p>}
            <button type="submit" class="btn-primary" disabled={loading}>
              {loading ? 'Authenticating…' : 'Sign in'}
            </button>
          </form>
        ) : (
          <form onSubmit={handleAnonymous} class="login-form">
            <label htmlFor="display-name">Your display name</label>
            <input
              id="display-name"
              type="text"
              placeholder="e.g. Alice"
              value={displayName}
              onInput={(e) => setDisplayName((e.target as HTMLInputElement).value)}
              required
              minLength={2}
              maxLength={40}
            />
            <p class="login-hint">Guest access lets you view public presentations.</p>
            {error && <p class="error-msg" role="alert">{error}</p>}
            <button type="submit" class="btn-primary" disabled={loading}>
              {loading ? 'Creating session…' : 'Continue as guest'}
            </button>
          </form>
        )}
      </div>
    </div>
  );
}
